version: '3'

services:
  next-app:
    container_name: next-app-digi-product
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - NEXT_PUBLIC_API_URL
    deploy:
      resources:
        limits:
          cpus: '0.5'
