import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NextAuthProvider from './providers';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Digital Product Demo',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          {children}
          {/* <ColorSchemeScript /> */}
        </NextAuthProvider>
      </body>
    </html>
  );
}
